# Generated by Django 2.2.9 on 2020-02-08 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaieduhr', models.CharField(blank=True, max_length=256, null=True, verbose_name='hrEduPersonUniqueID')),
                ('institution', models.CharField(blank=True, max_length=256, null=True, verbose_name='Institution')),
                ('role', models.CharField(blank=True, max_length=64, null=True, verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
