# Generated by Django 2.2.9 on 2020-02-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aaieduhr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='hrEduPersonUniqueID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Request update')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('request_date', models.DateTimeField(verbose_name='Request asked')),
                ('head_firstname', models.CharField(max_length=50, verbose_name='Head Firstname')),
                ('head_lastname', models.CharField(max_length=50, verbose_name='Head Lastname')),
                ('head_institution', models.CharField(max_length=200, verbose_name='Head Institution')),
                ('head_role', models.CharField(max_length=100, verbose_name='Head Role')),
                ('head_email', models.CharField(max_length=100, verbose_name='Head Email')),
                ('vm_purpose', models.TextField()),
                ('vm_os', models.CharField(max_length=50, verbose_name='VM OS')),
                ('vm_remark', models.TextField()),
                ('vm_fqdn', models.CharField(max_length=50, verbose_name='VM FQDN')),
                ('vm_reason', models.TextField()),
                ('vm_host', models.CharField(max_length=50, verbose_name='VM Host')),
                ('vm_ip', models.CharField(max_length=16, verbose_name='VM IP address')),
                ('vm_ready', models.IntegerField(verbose_name='VM Ready')),
                ('vm_dismissed', models.DateTimeField(verbose_name='VM Dismissed')),
                ('sys_firstname', models.CharField(max_length=50, verbose_name='Sys Firstname')),
                ('sys_lastname', models.CharField(max_length=50, verbose_name='Sys Lastname')),
                ('sys_institution', models.CharField(max_length=200, verbose_name='Sys Institution')),
                ('sys_role', models.CharField(max_length=100, verbose_name='Sys Role')),
                ('sys_email', models.CharField(max_length=100, verbose_name='Sys Email')),
                ('approved', models.IntegerField(verbose_name='Request Approved')),
                ('approvedby', models.CharField(max_length=100, verbose_name='Request Approved by')),
                ('approved_date', models.DateTimeField(verbose_name='VM Approved Date')),
                ('sys_aaieduhr', models.CharField(max_length=30, verbose_name='Sys AAIEduHR')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
