# Generated by Django 2.2.9 on 2020-02-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_add_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': (('approve_request', 'Can approve request'),)},
        ),
    ]
