# Generated by Django 2.2.9 on 2020-02-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_add_vmos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='vm_remark',
            new_name='vm_admin_remark',
        ),
    ]
