# Generated by Django 2.2.9 on 2020-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_vm_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='vm_remark',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
