# Generated by Django 2.2.9 on 2020-02-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_request_vm_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vm_dismissed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VM Dismissed'),
        ),
    ]
