# Generated by Django 2.2.9 on 2020-02-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_null_vm_dismiss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Request update'),
        ),
    ]
