# Generated by Django 2.2.9 on 2020-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_null_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VM Approved Date'),
        ),
    ]
