# Generated by Django 2.2.9 on 2020-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_null_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Request Approved'),
        ),
        migrations.AlterField(
            model_name='request',
            name='approvedby',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Request Approved by'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vm_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vm_host',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VM Host'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vm_ip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='VM IP address'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vm_ready',
            field=models.IntegerField(blank=True, null=True, verbose_name='VM Ready'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vm_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
