# Generated by Django 2.2.12 on 2020-04-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_request_vm_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='vm_host',
        ),
    ]
