# Generated by Django 2.2.12 on 2021-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0013_null_vm_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='vm_isactive',
            field=models.IntegerField(blank=True, null=True, default=5, verbose_name='Contact Response'),
        ),
        migrations.AddField(
            model_name='request',
            name='vm_isactive_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Response Comment'),
        ),
        migrations.AddField(
            model_name='request',
            name='vm_isactive_response',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contact Response Date'),
        ),
    ]
