devel:
	rm -rf bundles/reactbundle/* ; \
	node_modules/.bin/webpack --config webpack.config.js --progress --mode development

prod:
	rm -rf bundles/reactbundle/* ; \
	node_modules/.bin/webpack --config webpack.config.js --progress --mode production
